/**
 * Cliente Supabase para conexão com o banco de dados PostgreSQL
 *
 * COMO CONFIGURAR:
 * 1. Crie uma conta gratuita em https://supabase.com
 * 2. Crie um novo projeto
 * 3. Vá em Project Settings > API
 * 4. Copie a URL e a Anon Key
 * 5. Cole abaixo ou crie um arquivo .env
 */

import { createClient } from "@supabase/supabase-js";

// Configuração via variáveis de ambiente ou valores padrão
const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL || "https://seu-projeto.supabase.co";
const supabaseAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY || "sua-anon-key";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Configurações dos ramos de negócio disponíveis no sistema
 */
export const RAMOS_NEGOCIO = [
  {
    id: "padaria",
    nome: "Padaria / Confeitaria",
    icone: "fa-bread-slice",
    descricao: "Pães, bolos, salgados e produtos de confeitaria",
    cor: "#D4A574",
  },
  {
    id: "mercado",
    nome: "Mercado / Supermercado",
    icone: "fa-shopping-basket",
    descricao: "Alimentos, bebidas, limpeza e mercearia em geral",
    cor: "#4CAF50",
  },
  {
    id: "casa_racao",
    nome: "Casa de Ração / Pet Shop",
    icone: "fa-paw",
    descricao: "Rações, petiscos, acessórios e medicamentos para animais",
    cor: "#FF9800",
  },
  {
    id: "papelaria",
    nome: "Papelaria / Livraria",
    icone: "fa-book",
    descricao: "Material escolar, escritório, livros e papelaria em geral",
    cor: "#2196F3",
  },
  {
    id: "eletronicos",
    nome: "Eletrônicos / Informática",
    icone: "fa-laptop",
    descricao: "Celulares, computadores, acessórios e componentes",
    cor: "#9C27B0",
  },
  {
    id: "farmacia",
    nome: "Farmácia / Drogaria",
    icone: "fa-prescription-bottle",
    descricao: "Medicamentos, cosméticos, higiene e bem-estar",
    cor: "#00BCD4",
  },
  {
    id: "acougue",
    nome: "Açougue / Frigorífico",
    icone: "fa-drumstick-bite",
    descricao: "Carnes bovinas, suínas, aves e derivados",
    cor: "#F44336",
  },
  {
    id: "hortifruti",
    nome: "Hortifrúti / Sacolão",
    icone: "fa-carrot",
    descricao: "Frutas, verduras, legumes e produtos naturais",
    cor: "#8BC34A",
  },
  {
    id: "conveniencia",
    nome: "Loja de Conveniência",
    icone: "fa-store",
    descricao: "Bebidas, snacks, cigarros e produtos de conveniência",
    cor: "#795548",
  },
  {
    id: "vestuario",
    nome: "Vestuário / Moda",
    icone: "fa-tshirt",
    descricao: "Roupas, calçados, acessórios de moda",
    cor: "#E91E63",
  },
  {
    id: "variedades",
    nome: "Variedades",
    icone: "fa-gifts",
    descricao:
      "Produtos diversos - papelaria, eletrônicos, perfumes, brinquedos e muito mais",
    cor: "#FF5722",
  },
];

/**
 * Produtos padrão para cada ramo de negócio
 * Estes produtos são carregados automaticamente quando um novo tenant se cadastra
 */
export const PRODUTOS_PADRAO = {
  padaria: [
    {
      codigo: "001",
      descricao: "PÃO FRANCÊS (UN)",
      preco: 0.8,
      solicitarQuantidade: true,
      estoque: 100,
      estoqueMinimo: 20,
      categoria: "Pães",
    },
    {
      codigo: "002",
      descricao: "PÃO DE FORMA (PACOTE)",
      preco: 6.5,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 5,
      categoria: "Pães",
    },
    {
      codigo: "003",
      descricao: "BOLO DE CHOCOLATE (KG)",
      preco: 25.0,
      solicitarQuantidade: true,
      estoque: 5,
      estoqueMinimo: 2,
      categoria: "Bolos",
    },
    {
      codigo: "004",
      descricao: "BOLO DE CENOURA (KG)",
      preco: 22.0,
      solicitarQuantidade: true,
      estoque: 5,
      estoqueMinimo: 2,
      categoria: "Bolos",
    },
    {
      codigo: "005",
      descricao: "COXINHA (UN)",
      preco: 4.5,
      solicitarQuantidade: true,
      estoque: 50,
      estoqueMinimo: 10,
      categoria: "Salgados",
    },
    {
      codigo: "006",
      descricao: "ESFIRRA (UN)",
      preco: 5.0,
      solicitarQuantidade: true,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Salgados",
    },
    {
      codigo: "007",
      descricao: "PASTEL DE CARNE (UN)",
      preco: 6.0,
      solicitarQuantidade: true,
      estoque: 30,
      estoqueMinimo: 5,
      categoria: "Salgados",
    },
    {
      codigo: "008",
      descricao: "LEITE INTEGRAL 1L",
      preco: 4.8,
      solicitarQuantidade: false,
      estoque: 24,
      estoqueMinimo: 12,
      categoria: "Laticínios",
    },
    {
      codigo: "009",
      descricao: "CAFÉ EXPRESSO (XÍCARA)",
      preco: 3.5,
      solicitarQuantidade: false,
      estoque: 200,
      estoqueMinimo: 50,
      categoria: "Bebidas",
    },
    {
      codigo: "010",
      descricao: "PÃO DE QUEIJO (KG)",
      preco: 28.0,
      solicitarQuantidade: true,
      estoque: 8,
      estoqueMinimo: 3,
      categoria: "Pães",
    },
  ],
  mercado: [
    {
      codigo: "001",
      descricao: "ARROZ TIPO 1 5KG",
      preco: 22.9,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 10,
      categoria: "Grãos",
    },
    {
      codigo: "002",
      descricao: "FEIJÃO CARIOCA 1KG",
      preco: 7.5,
      solicitarQuantidade: false,
      estoque: 80,
      estoqueMinimo: 20,
      categoria: "Grãos",
    },
    {
      codigo: "003",
      descricao: "AÇÚCAR REFINADO 5KG",
      preco: 15.9,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Grãos",
    },
    {
      codigo: "004",
      descricao: "CAFÉ EM PÓ 500G",
      preco: 12.5,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 8,
      categoria: "Bebidas",
    },
    {
      codigo: "005",
      descricao: "LEITE INTEGRAL 1L",
      preco: 4.8,
      solicitarQuantidade: false,
      estoque: 60,
      estoqueMinimo: 24,
      categoria: "Laticínios",
    },
    {
      codigo: "006",
      descricao: "ÓLEO DE SOJA 900ML",
      preco: 6.9,
      solicitarQuantidade: false,
      estoque: 45,
      estoqueMinimo: 12,
      categoria: "Mercearia",
    },
    {
      codigo: "007",
      descricao: "REFRIGERANTE COLA 2L",
      preco: 8.5,
      solicitarQuantidade: false,
      estoque: 36,
      estoqueMinimo: 12,
      categoria: "Bebidas",
    },
    {
      codigo: "008",
      descricao: "SABÃO EM PÓ 1KG",
      preco: 10.5,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Limpeza",
    },
    {
      codigo: "009",
      descricao: "DETERGENTE LÍQUIDO 500ML",
      preco: 2.5,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 15,
      categoria: "Limpeza",
    },
    {
      codigo: "010",
      descricao: "MACARRÃO ESPAGUETE 500G",
      preco: 4.2,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Mercearia",
    },
  ],
  casa_racao: [
    {
      codigo: "001",
      descricao: "RAÇÃO CACHORRO ADULTO 15KG",
      preco: 89.9,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Rações",
    },
    {
      codigo: "002",
      descricao: "RAÇÃO GATO ADULTO 7.5KG",
      preco: 65.0,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Rações",
    },
    {
      codigo: "003",
      descricao: "RAÇÃO CACHORRO FILHOTE 15KG",
      preco: 99.9,
      solicitarQuantidade: false,
      estoque: 10,
      estoqueMinimo: 3,
      categoria: "Rações",
    },
    {
      codigo: "004",
      descricao: "PETISCO BIFINHO 100G",
      preco: 8.5,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Petiscos",
    },
    {
      codigo: "005",
      descricao: "AREIA SANITÁRIA 4KG",
      preco: 12.9,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Acessórios",
    },
    {
      codigo: "006",
      descricao: "ANTIPULGAS CACHORRO (COMP)",
      preco: 45.0,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Medicamentos",
    },
    {
      codigo: "007",
      descricao: "COLEIRA CACHORRO MÉDIO",
      preco: 25.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Acessórios",
    },
    {
      codigo: "008",
      descricao: "BRINQUEDO BOLA CACHORRO",
      preco: 15.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Brinquedos",
    },
    {
      codigo: "009",
      descricao: "RAÇÃO PEIXE 100G",
      preco: 6.5,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Rações",
    },
    {
      codigo: "010",
      descricao: "SHAMPOO CACHORRO 200ML",
      preco: 18.0,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Higiene",
    },
  ],
  papelaria: [
    {
      codigo: "001",
      descricao: "CADERNO UNIVERSITÁRIO 10 MATÉRIAS",
      preco: 25.9,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 10,
      categoria: "Cadernos",
    },
    {
      codigo: "002",
      descricao: "CANETA ESFEROGRÁFICA AZUL",
      preco: 1.5,
      solicitarQuantidade: true,
      estoque: 200,
      estoqueMinimo: 50,
      categoria: "Canetas",
    },
    {
      codigo: "003",
      descricao: "LÁPIS GRAPHITE HB",
      preco: 1.0,
      solicitarQuantidade: true,
      estoque: 150,
      estoqueMinimo: 30,
      categoria: "Lápis",
    },
    {
      codigo: "004",
      descricao: "BORRACHA BRANCA",
      preco: 2.0,
      solicitarQuantidade: false,
      estoque: 100,
      estoqueMinimo: 20,
      categoria: "Borracha",
    },
    {
      codigo: "005",
      descricao: "COLA BASTANTE 40G",
      preco: 4.5,
      solicitarQuantidade: false,
      estoque: 60,
      estoqueMinimo: 15,
      categoria: "Colas",
    },
    {
      codigo: "006",
      descricao: "TESOURA SEM PONTA",
      preco: 6.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 8,
      categoria: "Tesouras",
    },
    {
      codigo: "007",
      descricao: "RÉGUA 30CM",
      preco: 3.5,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Régua",
    },
    {
      codigo: "008",
      descricao: "MOCHILA ESCOLAR",
      preco: 89.9,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Mochilas",
    },
    {
      codigo: "009",
      descricao: "MARCA TEXTO AMARELO",
      preco: 3.0,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 10,
      categoria: "Canetas",
    },
    {
      codigo: "010",
      descricao: "PAPEL A4 500 FOLHAS",
      preco: 22.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Papéis",
    },
  ],
  eletronicos: [
    {
      codigo: "001",
      descricao: "CARREGADOR TIPO-C 20W",
      preco: 29.9,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Acessórios",
    },
    {
      codigo: "002",
      descricao: "FONE DE OUVIDO BLUETOOTH",
      preco: 79.9,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Áudio",
    },
    {
      codigo: "003",
      descricao: "PEN DRIVE 32GB",
      preco: 35.0,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Armazenamento",
    },
    {
      codigo: "004",
      descricao: "MOUSE USB ÓPTICO",
      preco: 25.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Periféricos",
    },
    {
      codigo: "005",
      descricao: "TECLADO USB SIMPLES",
      preco: 45.0,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Periféricos",
    },
    {
      codigo: "006",
      descricao: "CABO HDMI 2M",
      preco: 19.9,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Cabos",
    },
    {
      codigo: "007",
      descricao: "PELÍCULA DE VIDRO UNIVERSAL",
      preco: 12.0,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 15,
      categoria: "Acessórios",
    },
    {
      codigo: "008",
      descricao: "SUPORTE PARA CELULAR CARRO",
      preco: 22.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Acessórios",
    },
    {
      codigo: "009",
      descricao: "CAIXA DE SOM BLUETOOTH",
      preco: 59.9,
      solicitarQuantidade: false,
      estoque: 10,
      estoqueMinimo: 3,
      categoria: "Áudio",
    },
    {
      codigo: "010",
      descricao: "ADAPTADOR TOMADA UNIVERSAL",
      preco: 15.0,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Acessórios",
    },
  ],
  farmacia: [
    {
      codigo: "001",
      descricao: "PARACETAMOL 750MG 20CP",
      preco: 8.5,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 15,
      categoria: "Medicamentos",
    },
    {
      codigo: "002",
      descricao: "DIPIRONA 500MG 20CP",
      preco: 7.0,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 15,
      categoria: "Medicamentos",
    },
    {
      codigo: "003",
      descricao: "IBUPROFENO 600MG 20CP",
      preco: 12.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Medicamentos",
    },
    {
      codigo: "004",
      descricao: "PROTETOR SOLAR FPS 50 200ML",
      preco: 45.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Cosméticos",
    },
    {
      codigo: "005",
      descricao: "SHAMPOO ANTICASPA 200ML",
      preco: 18.0,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Higiene",
    },
    {
      codigo: "006",
      descricao: "FRALDA GERIÁTRICA M 8UN",
      preco: 22.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Fraldas",
    },
    {
      codigo: "007",
      descricao: "ALCOOL EM GEL 500ML",
      preco: 8.0,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 12,
      categoria: "Higiene",
    },
    {
      codigo: "008",
      descricao: "VITAMINA C 1G 30CP",
      preco: 25.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Suplementos",
    },
    {
      codigo: "009",
      descricao: "CURATIVO ADESIVO 10UN",
      preco: 3.5,
      solicitarQuantidade: false,
      estoque: 60,
      estoqueMinimo: 20,
      categoria: "Primeiros Socorros",
    },
    {
      codigo: "010",
      descricao: "MÁSCARA CIRÚRGICA 50UN",
      preco: 15.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Proteção",
    },
  ],
  acougue: [
    {
      codigo: "001",
      descricao: "PICANHA BOVINA (KG)",
      preco: 59.9,
      solicitarQuantidade: true,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Bovina",
    },
    {
      codigo: "002",
      descricao: "ALCATRA BOVINA (KG)",
      preco: 42.0,
      solicitarQuantidade: true,
      estoque: 25,
      estoqueMinimo: 5,
      categoria: "Bovina",
    },
    {
      codigo: "003",
      descricao: "COXÃO MOLE BOVINO (KG)",
      preco: 38.0,
      solicitarQuantidade: true,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Bovina",
    },
    {
      codigo: "004",
      descricao: "FRANGO INTEIRO (KG)",
      preco: 12.0,
      solicitarQuantidade: true,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Aves",
    },
    {
      codigo: "005",
      descricao: "PEITO DE FRANGO (KG)",
      preco: 18.0,
      solicitarQuantidade: true,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Aves",
    },
    {
      codigo: "006",
      descricao: "COSTELA BOVINA (KG)",
      preco: 28.0,
      solicitarQuantidade: true,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Bovina",
    },
    {
      codigo: "007",
      descricao: "LINGUIÇA TOSCANA (KG)",
      preco: 22.0,
      solicitarQuantidade: true,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Embutidos",
    },
    {
      codigo: "008",
      descricao: "CARNE MOÍDA BOVINA (KG)",
      preco: 25.0,
      solicitarQuantidade: true,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Bovina",
    },
    {
      codigo: "009",
      descricao: "PERNIL SUÍNO (KG)",
      preco: 18.0,
      solicitarQuantidade: true,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Suína",
    },
    {
      codigo: "010",
      descricao: "BISTECA SUÍNA (KG)",
      preco: 20.0,
      solicitarQuantidade: true,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Suína",
    },
  ],
  hortifruti: [
    {
      codigo: "001",
      descricao: "BANANA PRATA (KG)",
      preco: 4.5,
      solicitarQuantidade: true,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Frutas",
    },
    {
      codigo: "002",
      descricao: "MAÇÃ FUJI (KG)",
      preco: 6.0,
      solicitarQuantidade: true,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Frutas",
    },
    {
      codigo: "003",
      descricao: "LARANJA PERA (KG)",
      preco: 3.5,
      solicitarQuantidade: true,
      estoque: 40,
      estoqueMinimo: 15,
      categoria: "Frutas",
    },
    {
      codigo: "004",
      descricao: "ALFACE CRESPA (UN)",
      preco: 2.5,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Verduras",
    },
    {
      codigo: "005",
      descricao: "TOMATE (KG)",
      preco: 5.0,
      solicitarQuantidade: true,
      estoque: 20,
      estoqueMinimo: 8,
      categoria: "Legumes",
    },
    {
      codigo: "006",
      descricao: "CENOURA (KG)",
      preco: 3.0,
      solicitarQuantidade: true,
      estoque: 25,
      estoqueMinimo: 10,
      categoria: "Legumes",
    },
    {
      codigo: "007",
      descricao: "BATATA INGLESA (KG)",
      preco: 4.0,
      solicitarQuantidade: true,
      estoque: 50,
      estoqueMinimo: 20,
      categoria: "Legumes",
    },
    {
      codigo: "008",
      descricao: "CEBOLA (KG)",
      preco: 3.5,
      solicitarQuantidade: true,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Legumes",
    },
    {
      codigo: "009",
      descricao: "MAMÃO PAPAIA (UN)",
      preco: 5.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Frutas",
    },
    {
      codigo: "010",
      descricao: "COUVE (MAÇO)",
      preco: 2.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Verduras",
    },
  ],
  conveniencia: [
    {
      codigo: "001",
      descricao: "REFRIGERANTE COLA LATA 350ML",
      preco: 4.5,
      solicitarQuantidade: false,
      estoque: 72,
      estoqueMinimo: 24,
      categoria: "Bebidas",
    },
    {
      codigo: "002",
      descricao: "CERVEJA LATA 350ML",
      preco: 3.5,
      solicitarQuantidade: false,
      estoque: 48,
      estoqueMinimo: 24,
      categoria: "Bebidas",
    },
    {
      codigo: "003",
      descricao: "ÁGUA MINERAL 500ML",
      preco: 2.0,
      solicitarQuantidade: false,
      estoque: 48,
      estoqueMinimo: 24,
      categoria: "Bebidas",
    },
    {
      codigo: "004",
      descricao: "SALGADINHO DE MILHO 100G",
      preco: 3.0,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 15,
      categoria: "Snacks",
    },
    {
      codigo: "005",
      descricao: "BARRA DE CEREAL",
      preco: 2.5,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Snacks",
    },
    {
      codigo: "006",
      descricao: "CHOCOLATE AO LEITE 90G",
      preco: 5.5,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Doces",
    },
    {
      codigo: "007",
      descricao: "CIGARRO (MAÇO)",
      preco: 10.0,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 20,
      categoria: "Tabacaria",
    },
    {
      codigo: "008",
      descricao: "ISQUEIRO DESCARTÁVEL",
      preco: 2.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Tabacaria",
    },
    {
      codigo: "009",
      descricao: "PILHA AA 4UN",
      preco: 8.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Diversos",
    },
    {
      codigo: "010",
      descricao: "CHICLETE (UN)",
      preco: 0.5,
      solicitarQuantidade: true,
      estoque: 100,
      estoqueMinimo: 30,
      categoria: "Doces",
    },
  ],
  vestuario: [
    {
      codigo: "001",
      descricao: "CAMISETA BÁSICA MASCULINA",
      preco: 39.9,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Camisetas",
    },
    {
      codigo: "002",
      descricao: "CALÇA JEANS MASCULINA",
      preco: 89.9,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Calças",
    },
    {
      codigo: "003",
      descricao: "VESTIDO FEMININO",
      preco: 69.9,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Vestidos",
    },
    {
      codigo: "004",
      descricao: "BLUSA DE FRIO MASCULINA",
      preco: 59.9,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Blusas",
    },
    {
      codigo: "005",
      descricao: "SHORTS JEANS",
      preco: 45.0,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Shorts",
    },
    {
      codigo: "006",
      descricao: "TÊNIS CASUAL",
      preco: 129.9,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Calçados",
    },
    {
      codigo: "007",
      descricao: "SAPATO SOCIAL MASCULINO",
      preco: 149.9,
      solicitarQuantidade: false,
      estoque: 10,
      estoqueMinimo: 3,
      categoria: "Calçados",
    },
    {
      codigo: "008",
      descricao: "CINTO DE COURO",
      preco: 35.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Acessórios",
    },
    {
      codigo: "009",
      descricao: "BOLSA FEMININA",
      preco: 79.9,
      solicitarQuantidade: false,
      estoque: 12,
      estoqueMinimo: 3,
      categoria: "Acessórios",
    },
    {
      codigo: "010",
      descricao: "MEIAS 3 PARES",
      preco: 12.0,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Meias",
    },
  ],
  variedades: [
    {
      codigo: "001",
      descricao: "CADERNO UNIVERSITÁRIO 10 MATÉRIAS",
      preco: 25.9,
      solicitarQuantidade: false,
      estoque: 50,
      estoqueMinimo: 10,
      categoria: "Papelaria",
    },
    {
      codigo: "002",
      descricao: "CANETA ESFEROGRÁFICA AZUL",
      preco: 1.5,
      solicitarQuantidade: true,
      estoque: 200,
      estoqueMinimo: 50,
      categoria: "Papelaria",
    },
    {
      codigo: "003",
      descricao: "FONE DE OUVIDO BLUETOOTH",
      preco: 79.9,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Eletrônicos",
    },
    {
      codigo: "004",
      descricao: "CARREGADOR TIPO-C 20W",
      preco: 29.9,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Eletrônicos",
    },
    {
      codigo: "005",
      descricao: "PERFUME FEMININO 50ML",
      preco: 89.9,
      solicitarQuantidade: false,
      estoque: 15,
      estoqueMinimo: 5,
      categoria: "Perfumaria",
    },
    {
      codigo: "006",
      descricao: "DESODORANTE AEROSOL 150ML",
      preco: 12.0,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Perfumaria",
    },
    {
      codigo: "007",
      descricao: "BRINQUEDO CARRINHO (UN)",
      preco: 15.0,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Brinquedos",
    },
    {
      codigo: "008",
      descricao: "BONECA DE PANO (UN)",
      preco: 35.0,
      solicitarQuantidade: false,
      estoque: 12,
      estoqueMinimo: 3,
      categoria: "Brinquedos",
    },
    {
      codigo: "009",
      descricao: "CAMA CASAL SOLTEIRO (KIT)",
      preco: 149.9,
      solicitarQuantidade: false,
      estoque: 10,
      estoqueMinimo: 3,
      categoria: "Cama e Banho",
    },
    {
      codigo: "010",
      descricao: "TOALHA DE BANHO (UN)",
      preco: 39.9,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Cama e Banho",
    },
    {
      codigo: "011",
      descricao: "PEN DRIVE 32GB",
      preco: 35.0,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Eletrônicos",
    },
    {
      codigo: "012",
      descricao: "PILHA AA 4UN",
      preco: 8.0,
      solicitarQuantidade: false,
      estoque: 30,
      estoqueMinimo: 10,
      categoria: "Eletrônicos",
    },
    {
      codigo: "013",
      descricao: "CREME HIDRATANTE CORPORAL 200ML",
      preco: 22.0,
      solicitarQuantidade: false,
      estoque: 20,
      estoqueMinimo: 5,
      categoria: "Perfumaria",
    },
    {
      codigo: "014",
      descricao: "CHINELO DE DEDO (PAR)",
      preco: 19.9,
      solicitarQuantidade: false,
      estoque: 40,
      estoqueMinimo: 10,
      categoria: "Calçados",
    },
    {
      codigo: "015",
      descricao: "BONÉ (UN)",
      preco: 29.9,
      solicitarQuantidade: false,
      estoque: 25,
      estoqueMinimo: 8,
      categoria: "Vestuário",
    },
  ],
};

/**
 * Categorias padrão para cada ramo
 */
export const CATEGORIAS_PADRAO = {
  padaria: [
    "Pães",
    "Bolos",
    "Salgados",
    "Laticínios",
    "Bebidas",
    "Doces",
    "Café",
  ],
  mercado: [
    "Grãos",
    "Bebidas",
    "Laticínios",
    "Mercearia",
    "Limpeza",
    "Higiene",
    "Enlatados",
  ],
  casa_racao: [
    "Rações",
    "Petiscos",
    "Acessórios",
    "Medicamentos",
    "Brinquedos",
    "Higiene",
  ],
  papelaria: [
    "Cadernos",
    "Canetas",
    "Lápis",
    "Papéis",
    "Mochilas",
    "Tesouras",
    "Colas",
  ],
  eletronicos: [
    "Acessórios",
    "Áudio",
    "Armazenamento",
    "Periféricos",
    "Cabos",
    "Informática",
  ],
  farmacia: [
    "Medicamentos",
    "Cosméticos",
    "Higiene",
    "Suplementos",
    "Fraldas",
    "Proteção",
  ],
  acougue: ["Bovina", "Suína", "Aves", "Embutidos", "Frangos"],
  hortifruti: ["Frutas", "Verduras", "Legumes", "Temperos", "Orgânicos"],
  conveniencia: ["Bebidas", "Snacks", "Doces", "Tabacaria", "Diversos"],
  vestuario: [
    "Camisetas",
    "Calças",
    "Vestidos",
    "Blusas",
    "Calçados",
    "Acessórios",
    "Meias",
    "Shorts",
  ],
  variedades: [
    "Papelaria",
    "Eletrônicos",
    "Perfumaria",
    "Brinquedos",
    "Cama e Banho",
    "Calçados",
    "Vestuário",
    "Utilidades",
  ],
};
